version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/psbridge"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/runner"
    schedule:
      interval: "weekly"
