[[entries]]
date = 2025-08-19
packages = [
    "release_steamrip_24",
    "release_unix_24",
]

[[entries]]
date = 2024-08-19
packages = [
    "release_fitgirl_23",
]

[[entries]]
date = 2022-08-19
packages = [
    "release_off_16",
]
