package: {

    name: "WinDirStat" # "visual studio code"
    package_identifier: "windirstat" # "code" will convert to lower case ,pckage indentiy 
    description: "A disk usage statistics viewer and cleanup tool."
    homepage: "https://windirstat.net"
    license: "GPL-2.0-only"
    versioning: "semver"



}


release : {

    version: "2.5.0"
    url: "https://github.com/windirstat/windirstat/releases/download/release%2Fv2.5.0/WinDirStat.7z"
    hash: "1b399abe3b9f20e574f7c58b94c6530a34b6dfeec4bd89a6e2017abe62075614"

}